"""One-shot patch script: fix _run_comfyui_install_job for portable package layout."""
import pathlib

app_path = pathlib.Path(__file__).parent.parent / "app.py"
content = app_path.read_text(encoding="utf-8")

new_block = (
    "        # 2. Resolve the actual ComfyUI code root.\n"
    "        # Portable packages use: <configured_path>/ComfyUI/main.py\n"
    "        # Git-based installs use: <configured_path>/main.py\n"
    "        portable_sub = install_path / \"ComfyUI\"\n"
    "        if (portable_sub / \"main.py\").exists():\n"
    "            comfy_root = portable_sub\n"
    "            _append_install_log(job, \"\\n>>> Detected portable package layout\")\n"
    "            _append_install_log(job, f\"    ComfyUI root : {comfy_root}\")\n"
    "        else:\n"
    "            comfy_root = install_path\n"
    "\n"
    "        # 3. Clone if ComfyUI is not already present\n"
    "        main_py = comfy_root / \"main.py\"\n"
    "        if main_py.exists():\n"
    "            _append_install_log(job, \"\\n>>> Clone (skip - ComfyUI already present at target)\")\n"
    "        else:\n"
    "            comfy_root.parent.mkdir(parents=True, exist_ok=True)\n"
    "            ok = _run_install_step(\n"
    "                job, \"Clone ComfyUI\",\n"
    "                [\"git\", \"clone\", COMFYUI_REPO_URL, str(comfy_root)],\n"
    "                timeout=300,\n"
    "            )\n"
    "            if not ok:\n"
    "                raise RuntimeError(\"git clone failed - check log for details\")\n"
    "\n"
    "        # 4. Determine the Python executable.\n"
    "        # Portable packages ship with python_embeded which already has torch;\n"
    "        # for git-based installs we create a .venv and install torch ourselves.\n"
    "        embedded_python = comfy_root.parent / \"python_embeded\" / \"python.exe\"\n"
    "        has_embedded_python = os.name == \"nt\" and embedded_python.exists()\n"
    "\n"
    "        if has_embedded_python:\n"
    "            venv_python = str(embedded_python)\n"
    "            _append_install_log(job, f\"\\n>>> Using existing python_embeded: {venv_python}\")\n"
    "            _append_install_log(job, \">>> Create Python virtual environment (skip - portable package)\")\n"
    "            _append_install_log(job, \">>> Install PyTorch (skip - portable package has pre-installed torch)\")\n"
    "        else:\n"
    "            venv_dir = comfy_root / \".venv\"\n"
    "            if not venv_dir.exists():\n"
    "                ok = _run_install_step(\n"
    "                    job, \"Create Python virtual environment\",\n"
    "                    [sys.executable, \"-m\", \"venv\", str(venv_dir)],\n"
    "                    cwd=comfy_root,\n"
    "                    timeout=120,\n"
    "                )\n"
    "                if not ok:\n"
    "                    raise RuntimeError(\"venv creation failed - check log for details\")\n"
    "            else:\n"
    "                _append_install_log(job, \"\\n>>> Create Python virtual environment (skip - .venv already present)\")\n"
    "\n"
    "            venv_python = _find_comfyui_python(comfy_root)\n"
    "\n"
    "            _run_install_step(\n"
    "                job, \"Upgrade pip\",\n"
    "                [venv_python, \"-m\", \"pip\", \"install\", \"--upgrade\", \"pip\"],\n"
    "                cwd=comfy_root,\n"
    "                timeout=120,\n"
    "            )\n"
    "\n"
    "            torch_cmd = [venv_python, \"-m\", \"pip\", \"install\",\n"
    "                         \"torch\", \"torchvision\", \"torchaudio\"]\n"
    "            index_url = _TORCH_INDEX_URLS.get(gpu, \"\")\n"
    "            if index_url:\n"
    "                torch_cmd += [\"--index-url\", index_url]\n"
    "            ok = _run_install_step(job, f\"Install PyTorch ({gpu})\", torch_cmd,\n"
    "                                   cwd=comfy_root, timeout=600)\n"
    "            if not ok:\n"
    "                raise RuntimeError(\"torch install failed - check log for details\")\n"
    "\n"
    "        # 5. Install / update ComfyUI requirements\n"
    "        req_file = comfy_root / \"requirements.txt\"\n"
    "        if req_file.exists():\n"
    "            ok = _run_install_step(\n"
    "                job, \"Install ComfyUI requirements\",\n"
    "                [venv_python, \"-m\", \"pip\", \"install\", \"-r\", str(req_file)],\n"
    "                cwd=comfy_root,\n"
    "                timeout=600,\n"
    "            )\n"
    "            if not ok:\n"
    "                raise RuntimeError(\"requirements install failed - check log for details\")\n"
    "\n"
    "        # 6. Persist as comfyui_path in service config.\n"
    "        # Always save install_path (the portable root or git clone target) so that\n"
    "        # _resolve_comfyui_launch can detect the layout correctly.\n"
)

start = content.find("        # 2. Clone or skip if already present")
end = content.find("        # 7. Persist as comfyui_path in service config")

if start == -1 or end == -1:
    raise SystemExit(f"Markers not found: start={start}, end={end}")

print(f"Replacing chars {start}:{end} ({end - start} bytes)")
new_content = content[:start] + new_block + content[end:]
app_path.write_text(new_content, encoding="utf-8")
print(f"Done. File length: {len(new_content)} chars")
